# Generated by Django 4.1.7 on 2023-02-23 17:45

import appointment.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doctor', models.BooleanField(default=True)),
                ('speciality', models.CharField(choices=[('Allgemeinmedizin', 'Allgemeinmedizin'), ('Hautarzt', 'Hautarzt'), ('Radiologie', 'Radiologie')], max_length=50)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof. Dr.', 'Prof. Dr.'), ('Dr. rer. nat.', 'Dr. rer. nat.')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=datetime.datetime(2023, 2, 23, 18, 45, 10, 772373), default=datetime.datetime(2023, 2, 23, 18, 45, 10, 772373))),
                ('title', models.CharField(default='No title', max_length=50)),
                ('description', models.CharField(default='No description', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow, validators=[appointment.models.Appointment.validate_date])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patient')),
            ],
        ),
    ]
