# Generated by Django 4.1.7 on 2023-02-23 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 23, 18, 53, 55, 565435), default=datetime.datetime(2023, 2, 23, 18, 53, 55, 565435)),
        ),
    ]
